### ISSUE TITLE
I can't run this the first time because it complains that DebugKit isn't installed...

### ISSUE THREAD

**Issue by morrislaptop** [uzyn/cakephp-composer#7]

**Comment by uzyn** [comment]
Yes this is a known issue. It also due to CakePHP's behavior which requires that all plugins to be present before allowing any plugin to execute.

You can either use Composer directly (skipping this plugin totally), or temporarily comment out other `CakePlugin::load()` temporarily at your `app/Config/bootstrap.php` while you install the dependencies via Composer.

**Comment by morrislaptop** [comment]
Hey,

Yeah I was thinking that - I think I will use composer directly as we want
to auto deploy.

Cheers,
Craig

On Mon, Mar 4, 2013 at 12:53 PM, U-Zyn Chua notifications@github.comwrote:

> Yes this is a known issue. It also due to CakePHP's behavior which
> requires that all plugins to be present before allowing any plugin to
> execute.
> 
> You can either use Composer directly (skipping this plugin totally), or
> temporarily comment out other CakePlugin::load() temporarily at your
> app/Config/bootstrap.php while you install the dependencies via Composer.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/uzyn/cakephp-composer/issues/7#issuecomment-14360731
> .

## 

Craig Morris
0422 174 194 | craig.michael.morris@gmail.com | http://waww.com.au
http://au.linkedin.com/in/morrislaptop | http://www.twitter.com/morrislaptop|
http://www.facebook.com/morrislaptop

**Comment by uzyn** [comment]
Thanks.
